apiVersion: v1
kind: Service
metadata:
  name: ip-to-morse--service
spec:
  type: NodePort
  selector:
    app: ip-to-morse
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 80